kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rigor-pl
users:
- system:serviceaccount:<project-name>:rigor-agent
priority: 10
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "spc_t"
    level: "s0"
seccompProfiles:
- '*'
allowedCapabilities:
- NET_ADMIN
- NET_BROADCAST
fsGroup:
  type: MustRunAs
runAsUser:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
requiredDropCapabilities: []
